server {
  listen 8080;
  port_in_redirect off;
  absolute_redirect off;

  root   /usr/share/nginx/html;
  index  index.html index.htm;
  include /etc/nginx/mime.types;

  # Force browser to always check with network before serving index.html
  location = /index.html {
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    expires off;
  }

  location / {
      try_files $uri $uri/ /index.html;
  }
}
