"""add_youtube_url_to_source_assets

Revision ID: 582bbd507011
Revises: f7df23ff0c1d
Create Date: 2026-07-13 16:06:40.894364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '582bbd507011'
down_revision: Union[str, None] = 'f7df23ff0c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_assets', sa.Column('youtube_url', sa.String(), nullable=True))
    op.alter_column('source_assets', 'gcs_uri',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('source_assets', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('source_assets', 'mime_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('source_assets', 'file_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_assets', 'file_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('source_assets', 'mime_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('source_assets', 'original_filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('source_assets', 'gcs_uri',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('source_assets', 'youtube_url')
    # ### end Alembic commands ###
