"""Add adk_session_id to media_items

Revision ID: db1bd8b8d3eb
Revises: 3f709d6b793d
Create Date: 2026-03-12 07:34:12.548810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1bd8b8d3eb'
down_revision: Union[str, None] = '3f709d6b793d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('adk_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items', 'adk_session_id')
    # ### end Alembic commands ###
